# Site settings
title: SimpleUSM
email: mikko@usm.coach
description: >-
  An introductory guide to Unified Service Management (USM) - A universal,
  principle-based method for managing any service. Simple, practical, and free.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://simpleusm.com" # the base hostname & protocol for your site
twitter_username:
github_username:

# Book information
book:
  title: "Simple USM"
  subtitle: "A Practical Introduction to Unified Service Management"
  author: "Mikko Ahonen"
  coauthor: "with copious help from Jan van Bon"
  illustrator: "Kalle Ahonen"
  copyright: "© Copyright SURVUZ & Jauzo Oy 2021"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
