# Site settings
title: SimpleUSM
email: contact@simpleusm.com
description: >-
  Discover SimpleUSM - A comprehensive guide to understanding and implementing
  Unified Service Management in a simple, practical way.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: simpleusm
github_username: simpleusm

# Book information
book:
  title: "SimpleUSM"
  subtitle: "Making Unified Service Management Simple"
  author: "Your Name"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
